### ISSUE TITLE
DocumentView api reference?

### ISSUE THREAD

**Issue by peteruithoven** [thejambi/psnotes#14]
I really like psnotoes. I've switched to ElementaryOS from OS X and I was still looking for a good replacement for nvAlt and P.S. Notes seems to have a lot of potential. I was hoping to propose some style tweaks though. See: https://github.com/peteruithoven/psnotes/tree/style-tweaks
I've had little to no experience programming in Vala / GTK etc, and I'm having trouble finding the reference for the DocumentView you are using. I'm assuming it's from the `gtksourceview-3.0` package? 
I couldn't find it on https://valadoc.org or https://developer.gnome.org/gtksourceview/stable/

**Comment by thejambi** [comment]
Thanks! DocumentView is in the HyperTextView file, and ultimately it's a GtkSourceView. 

And yeah, P.S. Notes exists because I needed a tool that did what nvAlt does. So honestly this is something that I maintain for myself and I'm glad that others find it useful!

Let me know if you have any questions about anything. Thanks!

**Comment by peteruithoven** [comment]
Ah! Found it, thanks!
